### ISSUE TITLE
Arrow functions breaking for angular project in IE

### ISSUE THREAD

**Issue by rdandnayak** [sindresorhus/camelcase-keys#62] opened 2020-05-06 04:56 UTC
while running an angular project i face this problem
![image](https://user-images.githubusercontent.com/816239/81139567-ceb9eb00-8f83-11ea-9a4a-894ea3c43e87.png)

and the reason is
![image](https://user-images.githubusercontent.com/816239/81139521-a9c57800-8f83-11ea-9156-fb1bba9d3421.png)

seems like Arrow functions are not understandable  by IE11

**Comment by sindresorhus** [comment] 2020-05-06 05:51
Duplicate of #20

**Closed by sindresorhus** 2020-05-06 05:51 UTC

**Comment by cassianomon** [comment] 2020-11-19 17:38
Alternative function for Frontend projects:

```
function pascalToCamelCase(input) {
    let output, inputKey, outputKey, value;

    if (input instanceof Array) {
        return input.map((v) => (typeof v === 'object' ? pascalToCamelCase(v) : v));
    } else {
        output = {};
        for (inputKey in input) {
            if (input.hasOwnProperty(inputKey)) {
                outputKey = (
                    inputKey.charAt(0).toLowerCase() + inputKey.slice(1) ||
                    inputKey
                ).toString();

                value = input[inputKey];
                if (
                    value instanceof Array ||
                    (value !== null && value.constructor === Object)
                ) {
                    value = pascalToCamelCase(value);
                }
                output[outputKey] = value;
            }
        }
    }
    return output;
}

export default pascalToCamelCase;
```
