### ISSUE TITLE
type mismatch with reality

### ISSUE THREAD

**Issue by raidenmiro** [sindresorhus/camelcase-keys#113] opened 2023-08-24 12:56 UTC
If we transform an object like `{ ProjectID: '...' }`, he becomes `{ projectId: '...' }`. But by types, it becomes `projectID`.

Reproduce https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQIYgKYBs0GcMDSGAnrnAL5wBmUEIcA5AMbrYv4C0A1ibgwFD8YxMBjgAlDLgCuWeAF4UrHKnxFSAHgT84cAAq0AVhiYwAkgBEAXHFwwowAHYBzfuQB8gphEd24PLhtJGTl+AHow3SiAPQB+IA

**Comment by sindresorhus** [comment] 2023-08-24 16:31
Duplicate of https://github.com/sindresorhus/camelcase-keys/issues/88

**Closed** 2024-08-06 16:01 UTC
